Add craft_beer product category
csvalpha/sofia pull request #832
Opened 2022-12-01 14:16 UTC by wilco375

We would like to keep track of the craft beer revenue separately from normal beer. This PR adds a new category for that.

2022-12-06 18:55 UTC, Ellen-Wittingen requested changes
Hier is product-totalen bier 4.37 en speciaalbier 1.45
![image](https://user-images.githubusercontent.com/101463776/205996804-ebc2d5fe-f3d5-4de8-b101-51212b8330d0.png)
Hier bij samenvatting is bier 5.82 en speciaalbier niks. 
![image](https://user-images.githubusercontent.com/101463776/205997586-c3816eb6-7991-4f7b-a139-b069fa4c77cf.png)
Als je de totalen van bier en speciaalbier uit de product-totalen tabel pakt heb je 4.37 + 1.45 = 5.82, wat precies de bier omzet in de samenvatting is. Dus ik denk dat hier bier en speciaalbier niet gesplitst is.

2022-12-06 21:09 UTC, wilco375 commented
@Ellen-Wittingen heb je de categorie van speciaalbier aangepast in de prijslijst? (Of de database gereset?)

2022-12-07 19:37 UTC, Ellen-Wittingen commented
Categorie stond idd op bier in de prijslijst, excuses

2022-12-07 19:37 UTC, Ellen-Wittingen approved these changes

2022-12-07 22:03 UTC, merged